aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaavbbb
cccbbbcccccccccccccccccccccccccccccc
 fgfhghffhgghzzzzzzzzzzzcccccccccccccccvvvvvvvvvvvv
nnnnnnnnnnnnnnnnnnnnnnnnnncccccccccccc,,,,,,n
nnnnnnnnnnnnnnnnn
    vnvnbvn
nnnnnnnnnnn
    nnnnnnnnnnnn